name: Deploy to Production

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Deploy to server
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: 74.225.180.210
        username: me-frontend-user
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd /home/me-frontend-user/resume-viewer
          /home/me-frontend-user/scripts/deploy.sh